service: myservice

frameworkVersion: '2'
configValidationMode: off

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
    ${file(./configs/${self:provider.stage}.yml)}

plugins:
  - serverless-lift
  - serverless-offline-sqs
  - serverless-offline
  - serverless-ruby-layer

constructs:
  myFirstQueue:
    type: queue
    worker:
      handler: handler.second_function
      environment:
        QUEUE_URL: ${construct:mySecondQueue.queueUrl}
  
  mySecondQueue:
    type: queue
    worker:
      handler: handler.third_function


functions:
  first_function:
    handler: handler.first_function
    environment:
      QUEUE_URL: ${construct:myFirstQueue.queueUrl}

resources:
  Resources:
    myFirstQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: myFirstQueue

    mySecondQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: mySecondQueue

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}

  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false